"""
APEX — Tool Sync Script
========================
Keeps the 3 token-saving tools synchronized with the codebase.
Run after any code changes: python scripts/sync_tools.py

Updates:
  1. SPEC.md — Project specification (saves 50K tokens)
  2. CLAUDE.md + AGENTS.md — Agent context files
  3. docs/code_graph.html — Interactive architecture visualization
"""

import os
import re
import json
import shutil
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")


def scan_src():
    """Scan all source modules for current stats."""
    modules = {}
    for f in sorted(os.listdir(SRC)):
        if f.endswith(".py") and f != "__init__.py":
            path = os.path.join(SRC, f)
            with open(path, "r", encoding="utf-8") as fh:
                content = fh.read()
            classes = re.findall(r'^class\s+(\w+)', content, re.MULTILINE)
            functions = re.findall(r'^def\s+(\w+)', content, re.MULTILINE)
            lines = len(content.splitlines())
            modules[f.replace(".py", "")] = {
                "classes": classes,
                "functions": functions,
                "lines": lines,
            }
    return modules


def update_spec(modules):
    """Regenerate SPEC.md from current codebase."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # Build file table
    file_rows = []
    for name, info in modules.items():
        classes = ", ".join(info["classes"]) if info["classes"] else "—"
        file_rows.append(f"| src/{name}.py | {classes} | {info['lines']} |")
    file_table = "\n".join(file_rows)

    # Check data files
    data_info = ""
    raw_path = os.path.join(ROOT, "data", "structured_raw.json")
    cur_path = os.path.join(ROOT, "data", "curriculum.json")
    if os.path.exists(raw_path):
        with open(raw_path, "r", encoding="utf-8") as f:
            raw = json.load(f)
        data_info += f"- structured_raw.json: {raw.get('total_questions', '?')} questions, {len(raw.get('sections', []))} sections\n"
    if os.path.exists(cur_path):
        with open(cur_path, "r", encoding="utf-8") as f:
            cur = json.load(f)
        chapters = cur.get("chapters", [])
        total_concepts = sum(
            len(s.get("concepts", []))
            for ch in chapters for s in ch.get("sections", [])
        )
        data_info += f"- curriculum.json: {total_concepts} concepts\n"

    spec = f"""# APEX Curriculum Intelligence — Project Specification
# Auto-generated by sync_tools.py on {now}
# This file saves 50K+ tokens for any AI assistant reading the project.

## Architecture (5 Layers)

```
Layer 1: PDF Extractor   → src/docling_extractor.py (Docling, PDF→Markdown, Zero-AI)
Layer 2: AI Enricher     → src/ai_enricher.py       (Claude: Markdown→Curriculum JSON)
Layer 3: Knowledge Graph → src/graph_builder.py     (Neo4j)
Layer 4: Vector Search   → src/qdrant_store.py      (Hybrid: Dense+BM25+RRF)
Layer 5: RAG Engine      → src/rag_engine.py        (Multi-LLM)
```

## Source Files

| File | Classes | Lines |
|------|---------|-------|
{file_table}

## Data State

{data_info}

## Infrastructure

| Service | Port | Container |
|---------|------|-----------|
| Neo4j Browser | 7474 | apex-neo4j |
| Neo4j Bolt | 7687 | apex-neo4j |
| Qdrant REST | 6333 | apex-qdrant |

## Key Design Decisions

1. Docling-first extraction (IBM Docling: PDF→Markdown, then Claude for semantics)
2. Hybrid Search: Dense (semantic) + Sparse (BM25) + RRF fusion
3. Multi-LLM fallback: Gemini → Claude → Ollama
4. Bilingual support: Arabic + English content via Docling

## Commands

```bash
python -m src.docling_extractor "path/to/book.pdf"  # Extract PDF → Markdown (Docling)
python -m src.ai_enricher                            # Enrich with AI (from structured_raw)
python -m src.qdrant_store                           # Index hybrid vectors
python -m src.rag_engine                             # Interactive RAG
python scripts/sync_tools.py                         # Sync all tools
```
"""
    with open(os.path.join(ROOT, "SPEC.md"), "w", encoding="utf-8") as f:
        f.write(spec)
    print(f"  ✅ SPEC.md updated ({len(modules)} modules)")


def update_agents(modules):
    """Update CLAUDE.md and AGENTS.md."""
    now = datetime.now().strftime("%Y-%m-%d")
    module_list = "\n".join(f"  - src/{n}.py ({m['lines']} lines)" for n, m in modules.items())

    content = f"""# APEX Curriculum Intelligence — Agent Instructions
# Auto-synced: {now}

## Read SPEC.md for full project specification.

## Source Modules
{module_list}

## Key Principles
1. Docling-First Extraction: IBM Docling (PDF→Markdown), Claude only for semantics
2. Anti-Hallucination: RAG responses MUST cite curriculum sources
3. Bilingual: English + Arabic content via Docling
4. Clean Pipeline: PDF → Markdown → Curriculum JSON → SQLite

## Coding Standards
- Type hints on all public functions
- Rich console output for user feedback
- Pydantic models for data validation
"""
    for fname in ("CLAUDE.md", "AGENTS.md"):
        with open(os.path.join(ROOT, fname), "w", encoding="utf-8") as f:
            f.write(content)
    print(f"  ✅ CLAUDE.md + AGENTS.md updated")


def update_graph(modules):
    """Regenerate code_graph.html."""
    # Import and run the graph generator
    import importlib.util
    gen_path = os.path.join(ROOT, "toolchain", "understand", "generate.py")
    if os.path.exists(gen_path):
        spec = importlib.util.spec_from_file_location("generate", gen_path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        mod.generate_graph()
    else:
        print("  ⚠️ toolchain/understand/generate.py not found")


def main():
    print(f"🔄 APEX Tool Sync")
    print(f"{'='*40}")
    
    modules = scan_src()
    total_lines = sum(m["lines"] for m in modules.values())
    print(f"  📂 Scanned: {len(modules)} modules, {total_lines} total lines\n")
    
    update_spec(modules)
    update_agents(modules)
    update_graph(modules)
    
    print(f"\n{'='*40}")
    print(f"✅ All 3 tools synchronized!")
    print(f"   SPEC.md           — project specification")
    print(f"   CLAUDE/AGENTS.md  — agent context")
    print(f"   code_graph.html   — architecture visualization")


if __name__ == "__main__":
    main()
